# Generated by Django 2.0.7 on 2019-01-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('ip', models.GenericIPAddressField()),
                ('profile_pic', models.ImageField(height_field=100, upload_to='media/profile_pics', width_field=100)),
                ('isPremium', models.BooleanField(default=False)),
            ],
        ),
    ]
