# Generated by Django 2.0.7 on 2019-01-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip',
        ),
    ]
