# Generated by Django 2.0.7 on 2019-01-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='media/profile_pics'),
        ),
    ]
