# Generated by Django 2.0.7 on 2019-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
