# Generated by Django 2.0.7 on 2019-01-20 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190116_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
